# Generated by Django 3.0.8 on 2020-11-25 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.TextField()),
                ('date', models.DateField()),
                ('location', models.TextField()),
                ('time', models.TimeField()),
                ('report_title', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
    ]
